# docker-compose.yml
version: '3'

services:
  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: broker:9092
      OUTPUT_TOPIC: AAA
      TRANSACTIONS_PER_SECOND: 1000

  detector:
    build: ./detector
    environment:
      KAFKA_BROKER_URL: broker:9092
      TOPIC_INPUT: AAA
      TOPIC_OUTPUT: BBB
      DEPTH_LIMIT: 8
      DOWLOAND_DELAY: 0.3
      CLOSESPIDER_PAGECOUNT: 25
      AUTOTHROTTLE_ENABLE: 'true'
      AUTOTHROTTLE_TARGET_CONCURRENCY: 10
      MONGODB_ADDRESS: "mongodb:27017"
    volumes:
      - ./detector/data:/data
    external_links:
      - mongo

  destination:
    build: ./destination
    environment:
      KAFKA_BROKER_URL: broker:9092
      INPUT_TOPIC: BBB
# Give this composition access to the Kafka network
networks:
  default:
    external:
      name: kafka-network